In [2]:
import numpy as np
import pandas as pd
scroes = np.random.randint(50, 100,size=(50,5))
scores_df = pd.DataFrame(scroes,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores_df
sum_values = scores_df.sum(axis=1)
mean_values = scores_df.mean(axis=1)
scores_df['總分'] = sum_values
scores_df['平均'] = mean_values

In [4]:
scores_df.sort_values(by='總分')#排序總分

    國文  英文  數學  地理  歷史   總分    平均
7   61  66  54  56  55  292  58.4
39  74  55  66  60  52  307  61.4
1   65  58  74  59  56  312  62.4
47  63  50  71  69  62  315  63.0
43  81  50  58  50  85  324  64.8
50  99  52  57  52  68  328  65.6
3   67  74  74  66  59  340  68.0
44  71  67  52  79  71  340  68.0
9   95  56  53  83  54  341  68.2
19  58  72  87  71  54  342  68.4
40  79  81  72  55  56  343  68.6
2   65  72  52  97  61  347  69.4
31  74  55  52  85  82  348  69.6
37  52  94  98  50  54  348  69.6
49  72  67  80  62  71  352  70.4
46  73  63  91  70  56  353  70.6
27  77  59  79  81  58  354  70.8
34  87  66  52  55  96  356  71.2
45  84  75  65  69  63  356  71.2
11  50  86  70  95  55  356  71.2
35  63  90  55  52  97  357  71.4
6   53  65  92  54  93  357  71.4
48  84  84  75  65  53  361  72.2
10  65  72  80  88  58  363  72.6
28  67  99  71  55  71  363  72.6
29  55  88  83  87  51  364  72.8
15  95  70  71  74  55  365  73.0
21  79  94  76  68  51  368  73.6
36  87  68  63  74  77  369  73.8
4   59  86  51  85  92  373  74.6
42  51  54  80  94  99  378  75.6
13  99  64  96  65  54  378  75.6
17  73  76  82  94  55  380  76.0
18  71  52  92  79  89  383  76.6
14  57  81  96  65  88  387  77.4
41  97  90  62  73  65  387  77.4
5   61  90  62  85  91  389  77.8
32  84  63  60  95  88  390  78.0
38  72  90  72  75  82  391  78.2
12  79  88  86  70  68  391  78.2
16  85  89  81  67  70  392  78.4
24  89  88  90  69  58  394  78.8
20  73  93  81  76  81  404  80.8
33  95  51  85  87  87  405  81.0
23  60  91  76  87  93  407  81.4
30  53  79  98  99  81  410  82.0
26  99  88  75  99  52  413  82.6
8   83  74  74  96  87  414  82.8
25  86  87  93  89  69  424  84.8
22  89  93  86  77  84  429  85.8

In [18]:
scores_df.sort_values(by='總分',ascending=True).iloc[:5] #排序後5名總分

    國文  英文  數學  地理  歷史   總分    平均
7   61  66  54  56  55  292  58.4
39  74  55  66  60  52  307  61.4
1   65  58  74  59  56  312  62.4
47  63  50  71  69  62  315  63.0
43  81  50  58  50  85  324  64.8

In [19]:
scores_df.sort_values(by='總分',ascending=False).iloc[:5] #排序前5名總分

    國文  英文  數學  地理  歷史   總分    平均
22  89  93  86  77  84  429  85.8
25  86  87  93  89  69  424  84.8
8   83  74  74  96  87  414  82.8
26  99  88  75  99  52  413  82.6
30  53  79  98  99  81  410  82.0

In [24]:
#使用SUBSCRIPT()過瀘資料
scores_df[scores_df['平均'] < 80]

    國文  英文  數學  地理  歷史   總分    平均
1   65  58  74  59  56  312  62.4
2   65  72  52  97  61  347  69.4
3   67  74  74  66  59  340  68.0
4   59  86  51  85  92  373  74.6
5   61  90  62  85  91  389  77.8
6   53  65  92  54  93  357  71.4
7   61  66  54  56  55  292  58.4
9   95  56  53  83  54  341  68.2
10  65  72  80  88  58  363  72.6
11  50  86  70  95  55  356  71.2
12  79  88  86  70  68  391  78.2
13  99  64  96  65  54  378  75.6
14  57  81  96  65  88  387  77.4
15  95  70  71  74  55  365  73.0
16  85  89  81  67  70  392  78.4
17  73  76  82  94  55  380  76.0
18  71  52  92  79  89  383  76.6
19  58  72  87  71  54  342  68.4
21  79  94  76  68  51  368  73.6
24  89  88  90  69  58  394  78.8
27  77  59  79  81  58  354  70.8
28  67  99  71  55  71  363  72.6
29  55  88  83  87  51  364  72.8
31  74  55  52  85  82  348  69.6
32  84  63  60  95  88  390  78.0
34  87  66  52  55  96  356  71.2
35  63  90  55  52  97  357  71.4
36  87  68  63  74  77  369  73.8
37  52  94  98  50  54  348  69.6
38  72  90  72  75  82  391  78.2
39  74  55  66  60  52  307  61.4
40  79  81  72  55  56  343  68.6
41  97  90  62  73  65  387  77.4
42  51  54  80  94  99  378  75.6
43  81  50  58  50  85  324  64.8
44  71  67  52  79  71  340  68.0
45  84  75  65  69  63  356  71.2
46  73  63  91  70  56  353  70.6
47  63  50  71  69  62  315  63.0
48  84  84  75  65  53  361  72.2
49  72  67  80  62  71  352  70.4
50  99  52  57  52  68  328  65.6

In [25]:
#使用SUBSCRIPT()過瀘資料
scores_df[scores_df['平均'] < 80].count()

國文    42
英文    42
數學    42
地理    42
歷史    42
總分    42
平均    42
dtype: int64

In [32]:
#平均80以下，歷史不及格 使用subscrip[]的搜尋方法
scores_df[(scores_df['平均'] < 80) & (scores_df['歷史'] < 60)]

    國文  英文  數學  地理  歷史   總分    平均
1   65  58  74  59  56  312  62.4
3   67  74  74  66  59  340  68.0
7   61  66  54  56  55  292  58.4
9   95  56  53  83  54  341  68.2
10  65  72  80  88  58  363  72.6
11  50  86  70  95  55  356  71.2
13  99  64  96  65  54  378  75.6
15  95  70  71  74  55  365  73.0
17  73  76  82  94  55  380  76.0
19  58  72  87  71  54  342  68.4
21  79  94  76  68  51  368  73.6
24  89  88  90  69  58  394  78.8
27  77  59  79  81  58  354  70.8
29  55  88  83  87  51  364  72.8
37  52  94  98  50  54  348  69.6
39  74  55  66  60  52  307  61.4
40  79  81  72  55  56  343  68.6
46  73  63  91  70  56  353  70.6
48  84  84  75  65  53  361  72.2

In [28]:
#使用query(字串)方法
scores_df.query('平均<80')

    國文  英文  數學  地理  歷史   總分    平均
1   65  58  74  59  56  312  62.4
2   65  72  52  97  61  347  69.4
3   67  74  74  66  59  340  68.0
4   59  86  51  85  92  373  74.6
5   61  90  62  85  91  389  77.8
6   53  65  92  54  93  357  71.4
7   61  66  54  56  55  292  58.4
9   95  56  53  83  54  341  68.2
10  65  72  80  88  58  363  72.6
11  50  86  70  95  55  356  71.2
12  79  88  86  70  68  391  78.2
13  99  64  96  65  54  378  75.6
14  57  81  96  65  88  387  77.4
15  95  70  71  74  55  365  73.0
16  85  89  81  67  70  392  78.4
17  73  76  82  94  55  380  76.0
18  71  52  92  79  89  383  76.6
19  58  72  87  71  54  342  68.4
21  79  94  76  68  51  368  73.6
24  89  88  90  69  58  394  78.8
27  77  59  79  81  58  354  70.8
28  67  99  71  55  71  363  72.6
29  55  88  83  87  51  364  72.8
31  74  55  52  85  82  348  69.6
32  84  63  60  95  88  390  78.0
34  87  66  52  55  96  356  71.2
35  63  90  55  52  97  357  71.4
36  87  68  63  74  77  369  73.8
37  52  94  98  50  54  348  69.6
38  72  90  72  75  82  391  78.2
39  74  55  66  60  52  307  61.4
40  79  81  72  55  56  343  68.6
41  97  90  62  73  65  387  77.4
42  51  54  80  94  99  378  75.6
43  81  50  58  50  85  324  64.8
44  71  67  52  79  71  340  68.0
45  84  75  65  69  63  356  71.2
46  73  63  91  70  56  353  70.6
47  63  50  71  69  62  315  63.0
48  84  84  75  65  53  361  72.2
49  72  67  80  62  71  352  70.4
50  99  52  57  52  68  328  65.6

In [30]:
scores_df.query('平均<80 and 歷史<60')

    國文  英文  數學  地理  歷史   總分    平均
1   65  58  74  59  56  312  62.4
3   67  74  74  66  59  340  68.0
7   61  66  54  56  55  292  58.4
9   95  56  53  83  54  341  68.2
10  65  72  80  88  58  363  72.6
11  50  86  70  95  55  356  71.2
13  99  64  96  65  54  378  75.6
15  95  70  71  74  55  365  73.0
17  73  76  82  94  55  380  76.0
19  58  72  87  71  54  342  68.4
21  79  94  76  68  51  368  73.6
24  89  88  90  69  58  394  78.8
27  77  59  79  81  58  354  70.8
29  55  88  83  87  51  364  72.8
37  52  94  98  50  54  348  69.6
39  74  55  66  60  52  307  61.4
40  79  81  72  55  56  343  68.6
46  73  63  91  70  56  353  70.6
48  84  84  75  65  53  361  72.2